-- MySQL Script generated by MySQL Workbench
-- Wed 18 Oct 2023 10:27:42 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Library_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Library_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Library_DB` DEFAULT CHARACTER SET utf8 ;
USE `Library_DB` ;

-- -----------------------------------------------------
-- Table `Library_DB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`User` (
  `uid` INT NOT NULL,
  `fname` VARCHAR(16) NOT NULL,
  `mname` VARCHAR(16) NULL,
  `lname` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `is_faculty` TINYINT NOT NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Administrator` (
  `aid` INT NOT NULL,
  `afname` VARCHAR(16) NOT NULL,
  `amname` VARCHAR(16) NULL,
  `alname` VARCHAR(16) NOT NULL,
  `apassword` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Books` (
  `bid` INT NOT NULL,
  `btitle` TINYTEXT NOT NULL,
  `isbn` INT NOT NULL,
  `author_fname` VARCHAR(45) NOT NULL,
  `author_mname` VARCHAR(45) NULL,
  `author_lname` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `bownerid` INT NULL,
  PRIMARY KEY (`bid`),
  INDEX `bownerid_idx` (`bownerid` ASC) VISIBLE,
  CONSTRAINT `bownerid`
    FOREIGN KEY (`bownerid`)
    REFERENCES `Library_DB`.`User` (`uid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Devices` (
  `did` INT NOT NULL,
  `dtitle` TINYTEXT NOT NULL,
  `dcategory` VARCHAR(16) NOT NULL,
  `downerid` INT NULL,
  PRIMARY KEY (`did`),
  INDEX `downerid_idx` (`downerid` ASC) VISIBLE,
  CONSTRAINT `downerid`
    FOREIGN KEY (`downerid`)
    REFERENCES `Library_DB`.`User` (`uid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Media` (
  `mid` INT NOT NULL,
  `mtitle` TINYTEXT NOT NULL,
  `mcategory` VARCHAR(16) NOT NULL,
  `mownerid` INT NULL,
  PRIMARY KEY (`mid`),
  INDEX `mownerid_idx` (`mownerid` ASC) VISIBLE,
  CONSTRAINT `mownerid`
    FOREIGN KEY (`mownerid`)
    REFERENCES `Library_DB`.`User` (`uid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Book Fine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Book Fine` (
  `bfid` INT NOT NULL,
  `bfreason` VARCHAR(45) NOT NULL,
  `bfoverdue` INT NOT NULL,
  `bflost` INT NOT NULL,
  `bfdamaged` INT NOT NULL,
  `bfownerid` INT NOT NULL,
  PRIMARY KEY (`bfid`),
  INDEX `bfownerid_idx` (`bfownerid` ASC) VISIBLE,
  CONSTRAINT `bfownerid`
    FOREIGN KEY (`bfownerid`)
    REFERENCES `Library_DB`.`User` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Media Fine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Media Fine` (
  `fid` INT NOT NULL,
  `freason` VARCHAR(45) NOT NULL,
  `mflost` INT NOT NULL,
  `mfoverdue` INT NOT NULL,
  `mfdamaged` INT NOT NULL,
  `mfownerid` INT NOT NULL,
  PRIMARY KEY (`fid`),
  INDEX `mfownerid_idx` (`mfownerid` ASC) VISIBLE,
  CONSTRAINT `mfownerid`
    FOREIGN KEY (`mfownerid`)
    REFERENCES `Library_DB`.`User` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Library_DB`.`Device Fine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Library_DB`.`Device Fine` (
  `fid` INT NOT NULL,
  `freason` VARCHAR(45) NOT NULL,
  `dflost` INT NOT NULL,
  `dfdamaged` INT NOT NULL,
  `dfoverdue` INT NOT NULL,
  `dfownerid` INT NOT NULL,
  PRIMARY KEY (`fid`),
  INDEX `bfownerid_idx` (`dfownerid` ASC) VISIBLE,
  CONSTRAINT `bfownerid`
    FOREIGN KEY (`dfownerid`)
    REFERENCES `Library_DB`.`User` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
